### ISSUE TITLE
Add function hook to JS

### ISSUE THREAD

**Issue by OpherV** [Prinzhorn/skrollr#192]
It would be nice if you could add an option to add your own hooks for JS function. For example, I have a google map that I want to zoom in a certain part of the page scroll. 

Example format:

`addJsHook( startOffset, endOffset, easingFunc, executeFunc);`

where executeFuncis of the sort `function(percent) { }`

So if I call `addJsHook( 0, 500, "linear", function(percent) {  console.log(percent) }  );`
I would get 0 when scroll is top of page, 50 when scroll is 250px and 500 when scroll is 500px.

**Comment by minuz1991** [comment]
Hi,

I've got a problem. I'm trying to add event listeners to the elements. For example $('#element').on('click',function(){alert('some stuff')}); but I believe because elements are positioned absolutely and they are offset somewhere in the dom, I'm unable to click on the right thing and get the alert message. Is there a way to get element positions and be able to fire a function on click?
