### ISSUE TITLE
Pause Skrollr

### ISSUE THREAD

**Issue by vinnn** [Prinzhorn/skrollr#656]
Hi,
is it possible to "pause" scrollr? I would like to block/unblock vertical scrolling when clicking on a button. Second possibility would be to just pause the eventlistener which is checking for vertical scrolling. But somehow I dont seem to get the syntax right. 

Thanks a lot!
Vinnn

**Comment by Prinzhorn** [comment]
Since skrollr uses the native scrollbar you can achieve this from outside of skrollr.

Add `overflow:hidden` for desktop and `stopPropagation` for `touchstart`, `touchmove`, `toucheend` and `touchcancel` for mobile. The event listener needs to be below the document (e.g. body) so that skrollr never gets those.
