### ISSUE TITLE
rwww.win2.cn/g10

### ISSUE THREAD

**Issue by fa1c0n** [Prinzhorn/skrollr#667]

**Comment by kumarharsh** [comment]
spam?

**Comment by fa1c0n** [comment]
sorry guys, my mouse got crazy :( it inputs that symbols randomly. sorry!

**Comment by fa1c0n** [comment]
it's an accident. i'm sorry!

2015-01-27 14:29 GMT+02:00 Kumar Harsh <notifications@github.com>:

**Comment by kumarharsh** [comment]
Its OK. You can close the issue. That would be enough.

**Comment by johncant** [comment]
Entering this text is the default behaviour of extra buttons on some mice! Scary!

**Comment by kumarharsh** [comment]
OMG, really? That's very shady indeed --> `.cn`

**Comment by rsp** [comment]
@fa1c0n Where do you buy a mouse with a functionality to post issues on github with prefilled issue titles with your URLs? I want one.

**Comment by johncant** [comment]
It comes with an "internet helpdesk button". JK.

It acts as a keyboard and types the URL when you press the button. When I figure out how to fix it I'll post here so that other linux users don't suffer the same annoyance! Sorry about that - it's just that this URL is the 3rd item in the google search.
