### ISSUE TITLE
Translate3d Jerky in chrome (unsmooth)

### ISSUE THREAD

**Issue by jaydickinson** [Prinzhorn/skrollr#696]
Having some trouble with Translate3d being jerky in chrome when scrolling on trackpad or with mouse tested on macbook pro and macbook air.

I'm trying to translate a slider down when scrolling to give a parallax effect, I've knocked up a test page to demonstrate and it is jerky in chrome http://jakedickinson.co.uk/test

The image just flickers a lot is there anyway to smooth this out at all? 

I've just used: data-0="transform: translate3d(0px, 0px, 0px);" data-700="transform: translate3d(0px, 400px, 0px);"

Thanks

**Comment by Prinzhorn** [comment]
That's why the demo (https://github.com/Prinzhorn/skrollr/blob/master/examples/classic.html) positions the images fixed.
Your image is inside the document flow. That means

1. User scrolls
2. Image is scrolled up
3. Skrollr moves the image slightly down

What you notice is a slight delay between 2 and 3. In Firefox you won't notice this because of its smooth scrolling.

**Comment by jaydickinson** [comment]
Yeah I thought that might be the case.

Thanks
