### ISSUE TITLE
Skrollr on non-linear path?

### ISSUE THREAD

**Issue by verbatim** [Prinzhorn/skrollr#98]
http://joelb.me/blog/2012/jquery-scroll-path/
http://joelb.me/scrollpath/

With Skrollr, is there a way to move along a non-linear path, like this script ScrollPath?

**Comment by increed** [comment]
Heyy there..
I have used skrollr for my website. For data-attributes like data-0, data-700px, etc how to make the website responsive as per device widths? These attributes are used in line within html tags so cannot be used in css or javascript in order to make them responsive as per device widths. How is that to be achieved?

**Comment by Prinzhorn** [comment]
@increed 

relative mode: https://github.com/Prinzhorn/skrollr#relative-mode-or-viewport-mode
percentage offsets: https://github.com/Prinzhorn/skrollr#percentage-offsets
constants: https://github.com/Prinzhorn/skrollr#dynamic-constants

**Comment by increed** [comment]
Heyy Alex

I checked out the skrollr plugin for parallax wesbites. Its really awesome.

I have two doubts though:
1) How do you estimate the body height in parallax websites
2) How to make parallax site reponsive?. Since the viewport changes as per
the device widths. So if we define data attributes in pixels;that woudn't
work right?

Please guide me.

Thanks
Saroj

**Comment by increed** [comment]
Hi Alex,
As per your suggestion, I did try using percentage offsets and relative modes. But now the problem is skrollr does not work on mobiles in my case. Here is the link to what I have done so far:
http://divizbeta.in.s3-website-ap-southeast-1.amazonaws.com/
I used percentage offset here. And there is both horizontal and vertical scroll involved. So used css tranform property to translate the divs horizontally.

But, It is not responsive and neither does it work on mobiles. Any solutions for this?

Please help.
Thanks
Saroj
